In [3]:
import numpy as np
arr = np.ones((3,3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
import numpy as np
arr = np.linspace(5, 50, 10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [5]:
import numpy as np
py_list=[1, 2, 3, 4, 5]
arr = np.array(py_list)
print(arr)

[1 2 3 4 5]


In [9]:
import numpy as np
arr = np.arange(10)
print("Array:",arr)
print("Memory size in bytes:",arr.nbytes)

Array: [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes: 80


In [10]:
import numpy as np
arr = np.arange(10)
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [11]:
import numpy as np
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("The shape of the array is:", my_array.shape)
print("The number of dimensions of the array is:", my_array.ndim)
print("The size of each element in bytes is:", my_array.itemsize)

The shape of the array is: (4, 2)
The number of dimensions of the array is: 2
The size of each element in bytes is: 8


In [15]:
#printing a specific element from the array using slicing
import numpy as np
arr = np.arange(5,10)
print("Array:", arr[2:5])

Array: [7 8 9]


In [16]:
#printing a specific element from the array using indexing
import numpy as np
arr = np.arange(5,10)
print("Array:", arr[2])

Array: 7


In [17]:
#identity matrix
import numpy as np
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
import numpy as np
arr = np.arange(1,17).reshape(4,4)
print("Original array:\n", arr)
first_row = arr[0, :]
print("First row:", first_row)
last_column = arr[:, -1]
print("Last column:", last_column)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row: [1 2 3 4]
Last column: [ 4  8 12 16]


In [22]:
import numpy as np
arr = np.array([1,2,3,6,7,8,9,10])
extracted_elements = arr[(arr >= 5) & (arr <= 10)]
print("Extracted elements:", extracted_elements)

Extracted elements: [ 6  7  8  9 10]


In [25]:
import numpy as np
arr = np.arange(1,7).reshape(3,2)
print("Max:\n", arr.max())
print("Min:\n", arr.min())

Max:
 6
Min:
 1


In [28]:
import numpy as np
random_matrix = np.random.random((3, 2))
print("Random matrix:\n", random_matrix)
print("Maximum value:", random_matrix.max())
print("Minimum value:", random_matrix.min())

Random matrix:
 [[0.44123429 0.04828378]
 [0.47897522 0.09937041]
 [0.50667902 0.37734618]]
Maximum value: 0.5066790159227116
Minimum value: 0.04828377877244161
